# Generated by Django 2.1 on 2018-09-19 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('id',)},
        ),
    ]
