# Generated by Django 2.1 on 2018-09-16 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0002_technologysection'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='technology.TechnologySection'),
            preserve_default=False,
        ),
    ]
