# Generated by Django 2.1 on 2018-09-19 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0003_technology_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='technologysection',
            options={'ordering': ('id',)},
        ),
    ]
