sudo: required
language: generic

services:
  - docker

before_install:
  - echo "$GP_PASSWORD" | docker login docker.pkg.github.com -u "$GP_USERNAME" --password-stdin
  - if [[ "$TC_BRANCH_NAME" = "develop" ]] ; then export TC_BRANCH_NAME=; fi
  - touch .env
  - docker-compose pull || TC_BRANCH_NAME= docker-compose pull || true

before_script:
  - mkdir -p $(dirname "$REACT_STORE_DIR")
  - git clone --branch=togglecorp https://github.com/toggle-corp/react-store ${REACT_STORE_DIR}
  - cp ${REACT_STORE_DIR}/stylesheets/_user-imports-sample.scss ${REACT_STORE_DIR}/stylesheets/_user-imports.scss
  - git --git-dir=$REACT_STORE_DIR/.git --no-pager show --pretty=fuller --quiet
  - docker-compose build

script:
  - docker-compose run --rm server bash /code/scripts/run_tests.sh
  - echo "
    REACT_APP_API_END=${REACT_APP_API_END}
    " > .env
  - docker-compose run --rm client bash -c 'yarn install && CI=false yarn build'

after_success:
  - docker-compose push
  - |
    if [[ "$TRAVIS_BRANCH" = "release" ]] ; then
      docker pull $ZAPPA_IMG || true
      docker build -t $ZAPPA_IMG --cache-from $ZAPPA_IMG -f ./server/zappa.dockerfile ./server/
      docker run --rm \
          -e AWS_ACCESS_KEY_ID=$ZAPPA_AWS_ACCESS_KEY_ID \
          -e AWS_SECRET_ACCESS_KEY=$ZAPPA_AWS_SECRET_ACCESS_KEY \
          -e AWS_DEFAULT_REGION=$ZAPPA_AWS_DEFAULT_REGION \
          -v `pwd`/server/=/code/ \
        $ZAPPA_IMG \
        bash -c 'source /venv/bin/activate && cd /code/ && zappa update prod && zappa manage prod migrate'
      docker push $ZAPPA_IMG
    fi

deploy:
  provider: s3
  access_key_id: $ZAPPA_AWS_ACCESS_KEY_ID
  secret_access_key: $ZAPPA_AWS_SECRET_ACCESS_KEY
  bucket: $TOGGLECORP_S3_BUCKET
  skip_cleanup: true
  local_dir: ./client/build
  acl: public_read
  region: $ZAPPA_AWS_DEFAULT_REGION
  edge: true # opt in to dpl v2
  on:
    branch: release


env:
  global:
  - REACT_STORE_DIR=client/src/vendor/react-store
  - TC_BRANCH_NAME=`echo ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} | tr / _`
  - ZAPPA_IMG=docker.pkg.github.com/toggle-corp/togglecorp/zappa:latest
