version: '3.2'

services:
  db:
    image: postgres:9.6
    environment:
      # IMPORTANT: Remove this on production
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres-data:/var/lib/postgresql/data

  server:
    image: "docker.pkg.github.com/toggle-corp/togglecorp/tc-server:${TC_BRANCH_NAME:-develop}"
    build:
      context: ./server/
      cache_from:
        - "docker.pkg.github.com/toggle-corp/togglecorp/tc-server:${TC_BRANCH_NAME}"
        - docker.pkg.github.com/toggle-corp/togglecorp/tc-server:develop
    env_file:
      - .env
    command: bash -c '/code/scripts/wait-for-it.sh db:5432 && /code/scripts/run_develop.sh'
    volumes:
      - ./server/:/code
      - media:/media
    ports:
      - '8006:8006'
    depends_on:
      - db

  client:
    image: "docker.pkg.github.com/toggle-corp/togglecorp/tc-client:${TC_BRANCH_NAME:-develop}"
    build:
      context: ./client/
      cache_from:
        - "docker.pkg.github.com/toggle-corp/togglecorp/tc-client:${TC_BRANCH_NAME}"
        - docker.pkg.github.com/toggle-corp/togglecorp/tc-client:develop
    env_file:
      - .env
    command: bash -c '/code/scripts/run_develop.sh'
    volumes:
      - ./client/:/code
    ports:
      - '3006:3006'

volumes:
  media:
  postgres-data:
