# Generated by Django 2.2.6 on 2020-05-13 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='career',
            old_name='name',
            new_name='title',
        ),
    ]
