# Generated by Django 2.2.6 on 2020-05-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_auto_20200513_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
