# Generated by Django 2.2.6 on 2020-06-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_auto_20200517_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='hidden',
            field=models.BooleanField(default=False, help_text="Don't show this user"),
        ),
    ]
