# Generated by Django 2.1 on 2018-09-16 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberurl',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members_urls', to='member.Member'),
        ),
        migrations.AlterField(
            model_name='memberurl',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='member.MemberUrlType'),
        ),
        migrations.AlterField(
            model_name='memberurltype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
