# Generated by Django 2.1 on 2018-09-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20180916_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberurltype',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='member/url-icon/'),
        ),
    ]
