# Generated by Django 2.1 on 2019-05-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20180919_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='hide',
            field=models.BooleanField(default=False, help_text="Don't show this user"),
        ),
    ]
