# Generated by Django 2.1 on 2018-09-19 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20180917_0627'),
        ('client', '0003_auto_20180916_0945'),
        ('technology', '0003_technology_section'),
        ('service', '0001_initial'),
    ]

    operations = []
