# Generated by Django 2.1 on 2018-09-19 05:16

from django.db import migrations
from django.core.management import call_command


def load_initial_data(apps, schema_editor):
    call_command('load_initial_clients')
    call_command('load_initial_members')
    call_command('load_initial_services')
    call_command('load_initial_technologies')


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20180917_0627'),
        ('client', '0003_auto_20180916_0945'),
        ('technology', '0003_technology_section'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
