# Generated by Django 2.1 on 2018-09-19 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20180916_0945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('id',)},
        ),
    ]
